/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILottery,
  ILotteryInterface,
} from "../../../../contracts/mocks/co.sol/ILottery";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "usdtToken",
        type: "address",
      },
      {
        internalType: "uint8[6]",
        name: "winningNumbers",
        type: "uint8[6]",
      },
    ],
    name: "drawLottery",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "increase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILottery__factory {
  static readonly abi = _abi;
  static createInterface(): ILotteryInterface {
    return new Interface(_abi) as ILotteryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILottery {
    return new Contract(address, _abi, runner) as unknown as ILottery;
  }
}
