/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lottery from "./lottery";
export type { lottery };
import type * as mocks from "./mocks";
export type { mocks };
export type { InitFacet } from "./InitFacet";
