/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vrfConsumerAndAutomationLotterySol from "./VRFConsumerAndAutomationLottery.sol";
export type { vrfConsumerAndAutomationLotterySol };
