/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iCoinCaveLotterySol from "./ICoinCave_Lottery.sol";
export type { iCoinCaveLotterySol };
export type { ILink } from "./ILink";
