/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type MerkleTreesStruct = {
  grandPriceWinners: BytesLike;
  overUnderDrawWinners: BytesLike;
  matchDraw5Winners: BytesLike;
  matchDraw4Winners: BytesLike;
  matchDraw3Winners: BytesLike;
};

export type MerkleTreesStructOutput = [
  grandPriceWinners: string,
  overUnderDrawWinners: string,
  matchDraw5Winners: string,
  matchDraw4Winners: string,
  matchDraw3Winners: string
] & {
  grandPriceWinners: string;
  overUnderDrawWinners: string;
  matchDraw5Winners: string;
  matchDraw4Winners: string;
  matchDraw3Winners: string;
};

export type WinnersCountStruct = {
  grandPrizeWinnersCount: BigNumberish;
  overUnderDrawWinnersCount: BigNumberish;
  matchDraw5WinnersCount: BigNumberish;
  matchDraw4WinnersCount: BigNumberish;
  matchDraw3WinnersCount: BigNumberish;
};

export type WinnersCountStructOutput = [
  grandPrizeWinnersCount: bigint,
  overUnderDrawWinnersCount: bigint,
  matchDraw5WinnersCount: bigint,
  matchDraw4WinnersCount: bigint,
  matchDraw3WinnersCount: bigint
] & {
  grandPrizeWinnersCount: bigint;
  overUnderDrawWinnersCount: bigint;
  matchDraw5WinnersCount: bigint;
  matchDraw4WinnersCount: bigint;
  matchDraw3WinnersCount: bigint;
};

export interface CoinCave__LotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyCoins"
      | "checkUpkeep"
      | "claimPreviousRoundRewards"
      | "counter"
      | "drawLottery"
      | "drawRandomNumbers"
      | "enter"
      | "flipLotteryState"
      | "getCurrentRoundId"
      | "getCurrentTicketId"
      | "getLotteryStatus"
      | "getRoundDetails"
      | "getTicketWinningType"
      | "getUser"
      | "getUserTickets"
      | "getWinnerRoots"
      | "getWinnersCount"
      | "increase"
      | "initializeLottery"
      | "interval"
      | "lastRequestId"
      | "lastTimeStamp"
      | "performUpkeep"
      | "rawFulfillRandomWords"
      | "round"
      | "s_forwarderAddress"
      | "s_requests"
      | "setForwarderAddress"
      | "setWinnersCount"
      | "setWinnersRoots"
      | "totalPot"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CC_Lottery_AddCoinsToProfile"
      | "CC__Lottery_Entered"
      | "Calculated"
      | "Claimed"
      | "CounterCalled"
      | "DrawLottery"
      | "PlatformAndLPShare"
      | "PreviousRoundUnusedFundsCut"
      | "PriceWon"
      | "RaffleRandomNumber"
      | "RequestFulfilled"
      | "RequestSent"
      | "RewardClaimed"
      | "SetWinnerCount"
      | "UserParticipated"
      | "WinnersSetted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyCoins",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPreviousRoundRewards",
    values: [BigNumberish, BigNumberish, AddressLike, BytesLike[], AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "counter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "drawLottery",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drawRandomNumbers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enter",
    values: [
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flipLotteryState",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentTicketId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLotteryStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoundDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketWinningType",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTickets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnerRoots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnersCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "increase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initializeLottery",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "interval", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastTimeStamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "round", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_forwarderAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setForwarderAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWinnersCount",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setWinnersRoots",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyCoins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPreviousRoundRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "counter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drawLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawRandomNumbers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "flipLotteryState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLotteryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoundDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketWinningType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnerRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "increase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "interval", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTimeStamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "round", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_forwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWinnersRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace CC_Lottery_AddCoinsToProfileEvent {
  export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [buyer: string, amount: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CC__Lottery_EnteredEvent {
  export type InputTuple = [player: AddressLike, coinsAmount: BigNumberish];
  export type OutputTuple = [player: string, coinsAmount: bigint];
  export interface OutputObject {
    player: string;
    coinsAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CalculatedEvent {
  export type InputTuple = [amount: BigNumberish, where: string];
  export type OutputTuple = [amount: bigint, where: string];
  export interface OutputObject {
    amount: bigint;
    where: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    roundId: BigNumberish,
    winner: AddressLike,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: bigint,
    roundId: bigint,
    winner: string,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    ticketId: bigint;
    roundId: bigint;
    winner: string;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CounterCalledEvent {
  export type InputTuple = [
    count: BigNumberish,
    caller: AddressLike,
    txOrgin: AddressLike
  ];
  export type OutputTuple = [count: bigint, caller: string, txOrgin: string];
  export interface OutputObject {
    count: bigint;
    caller: string;
    txOrgin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawLotteryEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    winningNumbers: BigNumberish[]
  ];
  export type OutputTuple = [roundId: bigint, winningNumbers: bigint[]];
  export interface OutputObject {
    roundId: bigint;
    winningNumbers: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformAndLPShareEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    platformShare: BigNumberish,
    lpShare: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    platformShare: bigint,
    lpShare: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    platformShare: bigint;
    lpShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PreviousRoundUnusedFundsCutEvent {
  export type InputTuple = [
    toRound: BigNumberish,
    fromRound: BigNumberish,
    share: BigNumberish
  ];
  export type OutputTuple = [toRound: bigint, fromRound: bigint, share: bigint];
  export interface OutputObject {
    toRound: bigint;
    fromRound: bigint;
    share: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceWonEvent {
  export type InputTuple = [
    user: AddressLike,
    amountOfReward: BigNumberish,
    total: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    user: string,
    amountOfReward: bigint,
    total: bigint,
    reason: string
  ];
  export interface OutputObject {
    user: string;
    amountOfReward: bigint;
    total: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaffleRandomNumberEvent {
  export type InputTuple = [raffleId: BigNumberish, randomNumber: BigNumberish];
  export type OutputTuple = [raffleId: bigint, randomNumber: bigint];
  export interface OutputObject {
    raffleId: bigint;
    randomNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestFulfilledEvent {
  export type InputTuple = [
    round: BigNumberish,
    randomNumber: BigNumberish[],
    requestId: BigNumberish
  ];
  export type OutputTuple = [
    round: bigint,
    randomNumber: bigint[],
    requestId: bigint
  ];
  export interface OutputObject {
    round: bigint;
    randomNumber: bigint[];
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestSentEvent {
  export type InputTuple = [requestId: BigNumberish, numWords: BigNumberish];
  export type OutputTuple = [requestId: bigint, numWords: bigint];
  export interface OutputObject {
    requestId: bigint;
    numWords: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    roundId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, roundId: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    roundId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetWinnerCountEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    grandPriceWinnersCount: BigNumberish,
    overUnderDrawWinnersCount: BigNumberish,
    matchDraw5WinnersCount: BigNumberish,
    matchDraw4WinnersCount: BigNumberish,
    matchDraw3WinnersCount: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    grandPriceWinnersCount: bigint,
    overUnderDrawWinnersCount: bigint,
    matchDraw5WinnersCount: bigint,
    matchDraw4WinnersCount: bigint,
    matchDraw3WinnersCount: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    grandPriceWinnersCount: bigint;
    overUnderDrawWinnersCount: bigint;
    matchDraw5WinnersCount: bigint;
    matchDraw4WinnersCount: bigint;
    matchDraw3WinnersCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserParticipatedEvent {
  export type InputTuple = [
    user: AddressLike,
    roundId: BigNumberish,
    totalCoins: BigNumberish,
    numbers: BigNumberish[],
    _ovType: BigNumberish,
    ticketId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    roundId: bigint,
    totalCoins: bigint,
    numbers: bigint[],
    _ovType: bigint,
    ticketId: bigint
  ];
  export interface OutputObject {
    user: string;
    roundId: bigint;
    totalCoins: bigint;
    numbers: bigint[];
    _ovType: bigint;
    ticketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnersSettedEvent {
  export type InputTuple = [message: string];
  export type OutputTuple = [message: string];
  export interface OutputObject {
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoinCave__Lottery extends BaseContract {
  connect(runner?: ContractRunner | null): CoinCave__Lottery;
  waitForDeployment(): Promise<this>;

  interface: CoinCave__LotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyCoins: TypedContractMethod<
    [_amount: BigNumberish, _token: AddressLike],
    [void],
    "payable"
  >;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string]],
    "nonpayable"
  >;

  claimPreviousRoundRewards: TypedContractMethod<
    [
      _ticketId: BigNumberish,
      _roundId: BigNumberish,
      _user: AddressLike,
      _merkleProof: BytesLike[],
      _usdtToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  counter: TypedContractMethod<[], [bigint], "view">;

  drawLottery: TypedContractMethod<
    [_usdtToken: AddressLike],
    [void],
    "nonpayable"
  >;

  drawRandomNumbers: TypedContractMethod<[], [void], "nonpayable">;

  enter: TypedContractMethod<
    [
      _numbers: BigNumberish[],
      _grandPrizeCoins: BigNumberish,
      _matchDrawCoins: BigNumberish,
      _overUnderDrawCoins: BigNumberish,
      _ovType: BigNumberish,
      _matchDraw: boolean,
      _overUnderDraw: boolean
    ],
    [void],
    "nonpayable"
  >;

  flipLotteryState: TypedContractMethod<
    [_state: boolean],
    [void],
    "nonpayable"
  >;

  getCurrentRoundId: TypedContractMethod<[], [bigint], "view">;

  getCurrentTicketId: TypedContractMethod<
    [_roundId: BigNumberish],
    [bigint],
    "view"
  >;

  getLotteryStatus: TypedContractMethod<[], [boolean], "view">;

  getRoundDetails: TypedContractMethod<
    [_roundId: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;

  getTicketWinningType: TypedContractMethod<
    [_ticketId: BigNumberish, _roundId: BigNumberish],
    [bigint],
    "view"
  >;

  getUser: TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getUserTickets: TypedContractMethod<
    [_user: AddressLike, _roundId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getWinnerRoots: TypedContractMethod<
    [_roundId: BigNumberish],
    [MerkleTreesStructOutput],
    "view"
  >;

  getWinnersCount: TypedContractMethod<
    [_roundId: BigNumberish],
    [WinnersCountStructOutput],
    "view"
  >;

  increase: TypedContractMethod<[], [void], "nonpayable">;

  initializeLottery: TypedContractMethod<[], [void], "nonpayable">;

  interval: TypedContractMethod<[], [bigint], "view">;

  lastRequestId: TypedContractMethod<[], [bigint], "view">;

  lastTimeStamp: TypedContractMethod<[], [bigint], "view">;

  performUpkeep: TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  round: TypedContractMethod<[], [bigint], "view">;

  s_forwarderAddress: TypedContractMethod<[], [string], "view">;

  s_requests: TypedContractMethod<
    [arg0: BigNumberish],
    [[boolean, boolean] & { fulfilled: boolean; exists: boolean }],
    "view"
  >;

  setForwarderAddress: TypedContractMethod<
    [forwarderAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setWinnersCount: TypedContractMethod<
    [
      _grandPrizeWinners: BigNumberish,
      _overUnderDrawWinners: BigNumberish,
      _matchDraw5Winners: BigNumberish,
      _matchDraw4Winners: BigNumberish,
      _matchDraw3Winners: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setWinnersRoots: TypedContractMethod<
    [
      _grandPrizeWinners: BytesLike,
      _matchDraw5Winners: BytesLike,
      _matchDraw4Winners: BytesLike,
      _matchDraw3Winners: BytesLike,
      _overUnderDrawWinners: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  totalPot: TypedContractMethod<[_roundId: BigNumberish], [bigint], "view">;

  verify: TypedContractMethod<
    [_proof: BytesLike[], _tree: BytesLike, _leaf: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyCoins"
  ): TypedContractMethod<
    [_amount: BigNumberish, _token: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<[arg0: BytesLike], [[boolean, string]], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPreviousRoundRewards"
  ): TypedContractMethod<
    [
      _ticketId: BigNumberish,
      _roundId: BigNumberish,
      _user: AddressLike,
      _merkleProof: BytesLike[],
      _usdtToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "counter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drawLottery"
  ): TypedContractMethod<[_usdtToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "drawRandomNumbers"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enter"
  ): TypedContractMethod<
    [
      _numbers: BigNumberish[],
      _grandPrizeCoins: BigNumberish,
      _matchDrawCoins: BigNumberish,
      _overUnderDrawCoins: BigNumberish,
      _ovType: BigNumberish,
      _matchDraw: boolean,
      _overUnderDraw: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flipLotteryState"
  ): TypedContractMethod<[_state: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentRoundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentTicketId"
  ): TypedContractMethod<[_roundId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLotteryStatus"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoundDetails"
  ): TypedContractMethod<[_roundId: BigNumberish], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getTicketWinningType"
  ): TypedContractMethod<
    [_ticketId: BigNumberish, _roundId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTickets"
  ): TypedContractMethod<
    [_user: AddressLike, _roundId: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinnerRoots"
  ): TypedContractMethod<
    [_roundId: BigNumberish],
    [MerkleTreesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinnersCount"
  ): TypedContractMethod<
    [_roundId: BigNumberish],
    [WinnersCountStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "increase"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeLottery"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "interval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastTimeStamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "round"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_forwarderAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "s_requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[boolean, boolean] & { fulfilled: boolean; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setForwarderAddress"
  ): TypedContractMethod<[forwarderAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWinnersCount"
  ): TypedContractMethod<
    [
      _grandPrizeWinners: BigNumberish,
      _overUnderDrawWinners: BigNumberish,
      _matchDraw5Winners: BigNumberish,
      _matchDraw4Winners: BigNumberish,
      _matchDraw3Winners: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWinnersRoots"
  ): TypedContractMethod<
    [
      _grandPrizeWinners: BytesLike,
      _matchDraw5Winners: BytesLike,
      _matchDraw4Winners: BytesLike,
      _matchDraw3Winners: BytesLike,
      _overUnderDrawWinners: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalPot"
  ): TypedContractMethod<[_roundId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [_proof: BytesLike[], _tree: BytesLike, _leaf: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "CC_Lottery_AddCoinsToProfile"
  ): TypedContractEvent<
    CC_Lottery_AddCoinsToProfileEvent.InputTuple,
    CC_Lottery_AddCoinsToProfileEvent.OutputTuple,
    CC_Lottery_AddCoinsToProfileEvent.OutputObject
  >;
  getEvent(
    key: "CC__Lottery_Entered"
  ): TypedContractEvent<
    CC__Lottery_EnteredEvent.InputTuple,
    CC__Lottery_EnteredEvent.OutputTuple,
    CC__Lottery_EnteredEvent.OutputObject
  >;
  getEvent(
    key: "Calculated"
  ): TypedContractEvent<
    CalculatedEvent.InputTuple,
    CalculatedEvent.OutputTuple,
    CalculatedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CounterCalled"
  ): TypedContractEvent<
    CounterCalledEvent.InputTuple,
    CounterCalledEvent.OutputTuple,
    CounterCalledEvent.OutputObject
  >;
  getEvent(
    key: "DrawLottery"
  ): TypedContractEvent<
    DrawLotteryEvent.InputTuple,
    DrawLotteryEvent.OutputTuple,
    DrawLotteryEvent.OutputObject
  >;
  getEvent(
    key: "PlatformAndLPShare"
  ): TypedContractEvent<
    PlatformAndLPShareEvent.InputTuple,
    PlatformAndLPShareEvent.OutputTuple,
    PlatformAndLPShareEvent.OutputObject
  >;
  getEvent(
    key: "PreviousRoundUnusedFundsCut"
  ): TypedContractEvent<
    PreviousRoundUnusedFundsCutEvent.InputTuple,
    PreviousRoundUnusedFundsCutEvent.OutputTuple,
    PreviousRoundUnusedFundsCutEvent.OutputObject
  >;
  getEvent(
    key: "PriceWon"
  ): TypedContractEvent<
    PriceWonEvent.InputTuple,
    PriceWonEvent.OutputTuple,
    PriceWonEvent.OutputObject
  >;
  getEvent(
    key: "RaffleRandomNumber"
  ): TypedContractEvent<
    RaffleRandomNumberEvent.InputTuple,
    RaffleRandomNumberEvent.OutputTuple,
    RaffleRandomNumberEvent.OutputObject
  >;
  getEvent(
    key: "RequestFulfilled"
  ): TypedContractEvent<
    RequestFulfilledEvent.InputTuple,
    RequestFulfilledEvent.OutputTuple,
    RequestFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RequestSent"
  ): TypedContractEvent<
    RequestSentEvent.InputTuple,
    RequestSentEvent.OutputTuple,
    RequestSentEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SetWinnerCount"
  ): TypedContractEvent<
    SetWinnerCountEvent.InputTuple,
    SetWinnerCountEvent.OutputTuple,
    SetWinnerCountEvent.OutputObject
  >;
  getEvent(
    key: "UserParticipated"
  ): TypedContractEvent<
    UserParticipatedEvent.InputTuple,
    UserParticipatedEvent.OutputTuple,
    UserParticipatedEvent.OutputObject
  >;
  getEvent(
    key: "WinnersSetted"
  ): TypedContractEvent<
    WinnersSettedEvent.InputTuple,
    WinnersSettedEvent.OutputTuple,
    WinnersSettedEvent.OutputObject
  >;

  filters: {
    "CC_Lottery_AddCoinsToProfile(address,uint256)": TypedContractEvent<
      CC_Lottery_AddCoinsToProfileEvent.InputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputObject
    >;
    CC_Lottery_AddCoinsToProfile: TypedContractEvent<
      CC_Lottery_AddCoinsToProfileEvent.InputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputObject
    >;

    "CC__Lottery_Entered(address,uint256)": TypedContractEvent<
      CC__Lottery_EnteredEvent.InputTuple,
      CC__Lottery_EnteredEvent.OutputTuple,
      CC__Lottery_EnteredEvent.OutputObject
    >;
    CC__Lottery_Entered: TypedContractEvent<
      CC__Lottery_EnteredEvent.InputTuple,
      CC__Lottery_EnteredEvent.OutputTuple,
      CC__Lottery_EnteredEvent.OutputObject
    >;

    "Calculated(uint256,string)": TypedContractEvent<
      CalculatedEvent.InputTuple,
      CalculatedEvent.OutputTuple,
      CalculatedEvent.OutputObject
    >;
    Calculated: TypedContractEvent<
      CalculatedEvent.InputTuple,
      CalculatedEvent.OutputTuple,
      CalculatedEvent.OutputObject
    >;

    "Claimed(uint256,uint256,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "CounterCalled(uint256,address,address)": TypedContractEvent<
      CounterCalledEvent.InputTuple,
      CounterCalledEvent.OutputTuple,
      CounterCalledEvent.OutputObject
    >;
    CounterCalled: TypedContractEvent<
      CounterCalledEvent.InputTuple,
      CounterCalledEvent.OutputTuple,
      CounterCalledEvent.OutputObject
    >;

    "DrawLottery(uint256,uint8[6])": TypedContractEvent<
      DrawLotteryEvent.InputTuple,
      DrawLotteryEvent.OutputTuple,
      DrawLotteryEvent.OutputObject
    >;
    DrawLottery: TypedContractEvent<
      DrawLotteryEvent.InputTuple,
      DrawLotteryEvent.OutputTuple,
      DrawLotteryEvent.OutputObject
    >;

    "PlatformAndLPShare(uint256,uint256,uint256)": TypedContractEvent<
      PlatformAndLPShareEvent.InputTuple,
      PlatformAndLPShareEvent.OutputTuple,
      PlatformAndLPShareEvent.OutputObject
    >;
    PlatformAndLPShare: TypedContractEvent<
      PlatformAndLPShareEvent.InputTuple,
      PlatformAndLPShareEvent.OutputTuple,
      PlatformAndLPShareEvent.OutputObject
    >;

    "PreviousRoundUnusedFundsCut(uint256,uint256,uint256)": TypedContractEvent<
      PreviousRoundUnusedFundsCutEvent.InputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputObject
    >;
    PreviousRoundUnusedFundsCut: TypedContractEvent<
      PreviousRoundUnusedFundsCutEvent.InputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputObject
    >;

    "PriceWon(address,uint256,uint256,string)": TypedContractEvent<
      PriceWonEvent.InputTuple,
      PriceWonEvent.OutputTuple,
      PriceWonEvent.OutputObject
    >;
    PriceWon: TypedContractEvent<
      PriceWonEvent.InputTuple,
      PriceWonEvent.OutputTuple,
      PriceWonEvent.OutputObject
    >;

    "RaffleRandomNumber(uint256,uint256)": TypedContractEvent<
      RaffleRandomNumberEvent.InputTuple,
      RaffleRandomNumberEvent.OutputTuple,
      RaffleRandomNumberEvent.OutputObject
    >;
    RaffleRandomNumber: TypedContractEvent<
      RaffleRandomNumberEvent.InputTuple,
      RaffleRandomNumberEvent.OutputTuple,
      RaffleRandomNumberEvent.OutputObject
    >;

    "RequestFulfilled(uint256,uint256[],uint256)": TypedContractEvent<
      RequestFulfilledEvent.InputTuple,
      RequestFulfilledEvent.OutputTuple,
      RequestFulfilledEvent.OutputObject
    >;
    RequestFulfilled: TypedContractEvent<
      RequestFulfilledEvent.InputTuple,
      RequestFulfilledEvent.OutputTuple,
      RequestFulfilledEvent.OutputObject
    >;

    "RequestSent(uint256,uint32)": TypedContractEvent<
      RequestSentEvent.InputTuple,
      RequestSentEvent.OutputTuple,
      RequestSentEvent.OutputObject
    >;
    RequestSent: TypedContractEvent<
      RequestSentEvent.InputTuple,
      RequestSentEvent.OutputTuple,
      RequestSentEvent.OutputObject
    >;

    "RewardClaimed(address,uint256,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "SetWinnerCount(uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SetWinnerCountEvent.InputTuple,
      SetWinnerCountEvent.OutputTuple,
      SetWinnerCountEvent.OutputObject
    >;
    SetWinnerCount: TypedContractEvent<
      SetWinnerCountEvent.InputTuple,
      SetWinnerCountEvent.OutputTuple,
      SetWinnerCountEvent.OutputObject
    >;

    "UserParticipated(address,uint256,uint256,uint8[6],uint8,uint256)": TypedContractEvent<
      UserParticipatedEvent.InputTuple,
      UserParticipatedEvent.OutputTuple,
      UserParticipatedEvent.OutputObject
    >;
    UserParticipated: TypedContractEvent<
      UserParticipatedEvent.InputTuple,
      UserParticipatedEvent.OutputTuple,
      UserParticipatedEvent.OutputObject
    >;

    "WinnersSetted(string)": TypedContractEvent<
      WinnersSettedEvent.InputTuple,
      WinnersSettedEvent.OutputTuple,
      WinnersSettedEvent.OutputObject
    >;
    WinnersSetted: TypedContractEvent<
      WinnersSettedEvent.InputTuple,
      WinnersSettedEvent.OutputTuple,
      WinnersSettedEvent.OutputObject
    >;
  };
}
