/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coinCaveLotterySol from "./CoinCave_Lottery.sol";
export type { coinCaveLotterySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
