/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ICoinCave__LotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyCoins"
      | "calculatePrize"
      | "checkUpkeep"
      | "claimPreviousRoundRewards"
      | "drawLottery"
      | "enter"
      | "flipLotteryState"
      | "getCurrentRoundId"
      | "getIndividualTicketDetail"
      | "getLotteryStatus"
      | "getRoundDetails"
      | "getTicketWinningType"
      | "getUser"
      | "getUserTickets"
      | "getWinnerRoots"
      | "getWinnersCount"
      | "handlePlaftformShare"
      | "handlePreviousRoundUnusedFunds"
      | "increase"
      | "isAWonTicket"
      | "performUpkeep"
      | "setForwarderAddress"
      | "setWinnersCount"
      | "setWinnersRoots"
      | "totalPot"
      | "transferRewards"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CC_Lottery_AddCoinsToProfile"
      | "CC__Lottery_Entered"
      | "Calculated"
      | "Claimed"
      | "CounterCalled"
      | "DrawLottery"
      | "PlatformAndLPShare"
      | "PreviousRoundUnusedFundsCut"
      | "PriceWon"
      | "RewardClaimed"
      | "SetWinnerCount"
      | "UserParticipated"
      | "WinnersSetted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyCoins",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePrize",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPreviousRoundRewards",
    values: [BigNumberish, BigNumberish, AddressLike, BytesLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "drawLottery",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "enter",
    values: [
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flipLotteryState",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIndividualTicketDetail",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLotteryStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoundDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketWinningType",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTickets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnerRoots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnersCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handlePlaftformShare",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handlePreviousRoundUnusedFunds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "increase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isAWonTicket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setForwarderAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWinnersCount",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setWinnersRoots",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRewards",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "buyCoins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPreviousRoundRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "flipLotteryState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIndividualTicketDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLotteryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoundDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketWinningType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnerRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handlePlaftformShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handlePreviousRoundUnusedFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "increase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAWonTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWinnersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWinnersRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferRewards",
    data: BytesLike
  ): Result;
}

export namespace CC_Lottery_AddCoinsToProfileEvent {
  export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [buyer: string, amount: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CC__Lottery_EnteredEvent {
  export type InputTuple = [player: AddressLike, coinsAmount: BigNumberish];
  export type OutputTuple = [player: string, coinsAmount: bigint];
  export interface OutputObject {
    player: string;
    coinsAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CalculatedEvent {
  export type InputTuple = [amount: BigNumberish, where: string];
  export type OutputTuple = [amount: bigint, where: string];
  export interface OutputObject {
    amount: bigint;
    where: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    roundId: BigNumberish,
    winner: AddressLike,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: bigint,
    roundId: bigint,
    winner: string,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    ticketId: bigint;
    roundId: bigint;
    winner: string;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CounterCalledEvent {
  export type InputTuple = [
    count: BigNumberish,
    caller: AddressLike,
    txOrgin: AddressLike
  ];
  export type OutputTuple = [count: bigint, caller: string, txOrgin: string];
  export interface OutputObject {
    count: bigint;
    caller: string;
    txOrgin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawLotteryEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    winningNumbers: BigNumberish[]
  ];
  export type OutputTuple = [roundId: bigint, winningNumbers: bigint[]];
  export interface OutputObject {
    roundId: bigint;
    winningNumbers: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformAndLPShareEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    platformShare: BigNumberish,
    lpShare: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    platformShare: bigint,
    lpShare: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    platformShare: bigint;
    lpShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PreviousRoundUnusedFundsCutEvent {
  export type InputTuple = [
    toRound: BigNumberish,
    fromRound: BigNumberish,
    share: BigNumberish
  ];
  export type OutputTuple = [toRound: bigint, fromRound: bigint, share: bigint];
  export interface OutputObject {
    toRound: bigint;
    fromRound: bigint;
    share: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceWonEvent {
  export type InputTuple = [
    user: AddressLike,
    amountOfReward: BigNumberish,
    total: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    user: string,
    amountOfReward: bigint,
    total: bigint,
    reason: string
  ];
  export interface OutputObject {
    user: string;
    amountOfReward: bigint;
    total: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    roundId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, roundId: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    roundId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetWinnerCountEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    grandPriceWinnersCount: BigNumberish,
    overUnderDrawWinnersCount: BigNumberish,
    matchDraw5WinnersCount: BigNumberish,
    matchDraw4WinnersCount: BigNumberish,
    matchDraw3WinnersCount: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    grandPriceWinnersCount: bigint,
    overUnderDrawWinnersCount: bigint,
    matchDraw5WinnersCount: bigint,
    matchDraw4WinnersCount: bigint,
    matchDraw3WinnersCount: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    grandPriceWinnersCount: bigint;
    overUnderDrawWinnersCount: bigint;
    matchDraw5WinnersCount: bigint;
    matchDraw4WinnersCount: bigint;
    matchDraw3WinnersCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserParticipatedEvent {
  export type InputTuple = [
    user: AddressLike,
    roundId: BigNumberish,
    totalCoins: BigNumberish,
    numbers: BigNumberish[],
    ticketId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    roundId: bigint,
    totalCoins: bigint,
    numbers: bigint[],
    ticketId: bigint
  ];
  export interface OutputObject {
    user: string;
    roundId: bigint;
    totalCoins: bigint;
    numbers: bigint[];
    ticketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnersSettedEvent {
  export type InputTuple = [message: string];
  export type OutputTuple = [message: string];
  export interface OutputObject {
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICoinCave__Lottery extends BaseContract {
  connect(runner?: ContractRunner | null): ICoinCave__Lottery;
  waitForDeployment(): Promise<this>;

  interface: ICoinCave__LotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyCoins: TypedContractMethod<
    [amount: BigNumberish, token: AddressLike],
    [void],
    "payable"
  >;

  calculatePrize: TypedContractMethod<
    [roundId: BigNumberish, winningType: BigNumberish],
    [bigint],
    "view"
  >;

  checkUpkeep: TypedContractMethod<
    [checkData: BytesLike],
    [[boolean, string]],
    "nonpayable"
  >;

  claimPreviousRoundRewards: TypedContractMethod<
    [
      ticketId: BigNumberish,
      roundId: BigNumberish,
      user: AddressLike,
      merkleProof: BytesLike[],
      usdtToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  drawLottery: TypedContractMethod<
    [usdtToken: AddressLike, winningNumbers: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  enter: TypedContractMethod<
    [
      numbers: BigNumberish[],
      grandPrizeCoins: BigNumberish,
      matchDrawCoins: BigNumberish,
      overUnderDrawCoins: BigNumberish,
      ovType: BigNumberish,
      matchDraw: boolean,
      overUnderDraw: boolean
    ],
    [void],
    "nonpayable"
  >;

  flipLotteryState: TypedContractMethod<[state: boolean], [void], "nonpayable">;

  getCurrentRoundId: TypedContractMethod<[], [bigint], "view">;

  getIndividualTicketDetail: TypedContractMethod<
    [ticketId: BigNumberish, roundId: BigNumberish, user: AddressLike],
    [[bigint, bigint, bigint, bigint[], bigint, bigint]],
    "view"
  >;

  getLotteryStatus: TypedContractMethod<[], [boolean], "view">;

  getRoundDetails: TypedContractMethod<
    [roundId: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;

  getTicketWinningType: TypedContractMethod<
    [ticketId: BigNumberish, roundId: BigNumberish],
    [bigint],
    "view"
  >;

  getUser: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getUserTickets: TypedContractMethod<
    [user: AddressLike, roundId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getWinnerRoots: TypedContractMethod<
    [roundId: BigNumberish],
    [[string, string, string, string, string]],
    "view"
  >;

  getWinnersCount: TypedContractMethod<
    [roundId: BigNumberish],
    [[bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;

  handlePlaftformShare: TypedContractMethod<
    [usdtToken: AddressLike],
    [void],
    "nonpayable"
  >;

  handlePreviousRoundUnusedFunds: TypedContractMethod<[], [void], "nonpayable">;

  increase: TypedContractMethod<[], [void], "nonpayable">;

  isAWonTicket: TypedContractMethod<
    [roundId: BigNumberish, ticketId: BigNumberish],
    [boolean],
    "view"
  >;

  performUpkeep: TypedContractMethod<
    [performData: BytesLike],
    [void],
    "nonpayable"
  >;

  setForwarderAddress: TypedContractMethod<
    [forwarderAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setWinnersCount: TypedContractMethod<
    [
      grandPrizeWinners: BigNumberish,
      overUnderDrawWinners: BigNumberish,
      matchDraw5Winners: BigNumberish,
      matchDraw4Winners: BigNumberish,
      matchDraw3Winners: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setWinnersRoots: TypedContractMethod<
    [
      grandPrizeWinners: BytesLike,
      matchDraw5Winners: BytesLike,
      matchDraw4Winners: BytesLike,
      matchDraw3Winners: BytesLike,
      overUnderDrawWinners: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  totalPot: TypedContractMethod<[roundId: BigNumberish], [bigint], "view">;

  transferRewards: TypedContractMethod<
    [
      roundId: BigNumberish,
      prize: BigNumberish,
      usdtToken: AddressLike,
      ticketId: BigNumberish,
      winningType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyCoins"
  ): TypedContractMethod<
    [amount: BigNumberish, token: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "calculatePrize"
  ): TypedContractMethod<
    [roundId: BigNumberish, winningType: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [checkData: BytesLike],
    [[boolean, string]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimPreviousRoundRewards"
  ): TypedContractMethod<
    [
      ticketId: BigNumberish,
      roundId: BigNumberish,
      user: AddressLike,
      merkleProof: BytesLike[],
      usdtToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "drawLottery"
  ): TypedContractMethod<
    [usdtToken: AddressLike, winningNumbers: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enter"
  ): TypedContractMethod<
    [
      numbers: BigNumberish[],
      grandPrizeCoins: BigNumberish,
      matchDrawCoins: BigNumberish,
      overUnderDrawCoins: BigNumberish,
      ovType: BigNumberish,
      matchDraw: boolean,
      overUnderDraw: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flipLotteryState"
  ): TypedContractMethod<[state: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentRoundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getIndividualTicketDetail"
  ): TypedContractMethod<
    [ticketId: BigNumberish, roundId: BigNumberish, user: AddressLike],
    [[bigint, bigint, bigint, bigint[], bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLotteryStatus"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoundDetails"
  ): TypedContractMethod<[roundId: BigNumberish], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getTicketWinningType"
  ): TypedContractMethod<
    [ticketId: BigNumberish, roundId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTickets"
  ): TypedContractMethod<
    [user: AddressLike, roundId: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinnerRoots"
  ): TypedContractMethod<
    [roundId: BigNumberish],
    [[string, string, string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinnersCount"
  ): TypedContractMethod<
    [roundId: BigNumberish],
    [[bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "handlePlaftformShare"
  ): TypedContractMethod<[usdtToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "handlePreviousRoundUnusedFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "increase"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isAWonTicket"
  ): TypedContractMethod<
    [roundId: BigNumberish, ticketId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[performData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForwarderAddress"
  ): TypedContractMethod<[forwarderAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWinnersCount"
  ): TypedContractMethod<
    [
      grandPrizeWinners: BigNumberish,
      overUnderDrawWinners: BigNumberish,
      matchDraw5Winners: BigNumberish,
      matchDraw4Winners: BigNumberish,
      matchDraw3Winners: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWinnersRoots"
  ): TypedContractMethod<
    [
      grandPrizeWinners: BytesLike,
      matchDraw5Winners: BytesLike,
      matchDraw4Winners: BytesLike,
      matchDraw3Winners: BytesLike,
      overUnderDrawWinners: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalPot"
  ): TypedContractMethod<[roundId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferRewards"
  ): TypedContractMethod<
    [
      roundId: BigNumberish,
      prize: BigNumberish,
      usdtToken: AddressLike,
      ticketId: BigNumberish,
      winningType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CC_Lottery_AddCoinsToProfile"
  ): TypedContractEvent<
    CC_Lottery_AddCoinsToProfileEvent.InputTuple,
    CC_Lottery_AddCoinsToProfileEvent.OutputTuple,
    CC_Lottery_AddCoinsToProfileEvent.OutputObject
  >;
  getEvent(
    key: "CC__Lottery_Entered"
  ): TypedContractEvent<
    CC__Lottery_EnteredEvent.InputTuple,
    CC__Lottery_EnteredEvent.OutputTuple,
    CC__Lottery_EnteredEvent.OutputObject
  >;
  getEvent(
    key: "Calculated"
  ): TypedContractEvent<
    CalculatedEvent.InputTuple,
    CalculatedEvent.OutputTuple,
    CalculatedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CounterCalled"
  ): TypedContractEvent<
    CounterCalledEvent.InputTuple,
    CounterCalledEvent.OutputTuple,
    CounterCalledEvent.OutputObject
  >;
  getEvent(
    key: "DrawLottery"
  ): TypedContractEvent<
    DrawLotteryEvent.InputTuple,
    DrawLotteryEvent.OutputTuple,
    DrawLotteryEvent.OutputObject
  >;
  getEvent(
    key: "PlatformAndLPShare"
  ): TypedContractEvent<
    PlatformAndLPShareEvent.InputTuple,
    PlatformAndLPShareEvent.OutputTuple,
    PlatformAndLPShareEvent.OutputObject
  >;
  getEvent(
    key: "PreviousRoundUnusedFundsCut"
  ): TypedContractEvent<
    PreviousRoundUnusedFundsCutEvent.InputTuple,
    PreviousRoundUnusedFundsCutEvent.OutputTuple,
    PreviousRoundUnusedFundsCutEvent.OutputObject
  >;
  getEvent(
    key: "PriceWon"
  ): TypedContractEvent<
    PriceWonEvent.InputTuple,
    PriceWonEvent.OutputTuple,
    PriceWonEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SetWinnerCount"
  ): TypedContractEvent<
    SetWinnerCountEvent.InputTuple,
    SetWinnerCountEvent.OutputTuple,
    SetWinnerCountEvent.OutputObject
  >;
  getEvent(
    key: "UserParticipated"
  ): TypedContractEvent<
    UserParticipatedEvent.InputTuple,
    UserParticipatedEvent.OutputTuple,
    UserParticipatedEvent.OutputObject
  >;
  getEvent(
    key: "WinnersSetted"
  ): TypedContractEvent<
    WinnersSettedEvent.InputTuple,
    WinnersSettedEvent.OutputTuple,
    WinnersSettedEvent.OutputObject
  >;

  filters: {
    "CC_Lottery_AddCoinsToProfile(address,uint256)": TypedContractEvent<
      CC_Lottery_AddCoinsToProfileEvent.InputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputObject
    >;
    CC_Lottery_AddCoinsToProfile: TypedContractEvent<
      CC_Lottery_AddCoinsToProfileEvent.InputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputTuple,
      CC_Lottery_AddCoinsToProfileEvent.OutputObject
    >;

    "CC__Lottery_Entered(address,uint256)": TypedContractEvent<
      CC__Lottery_EnteredEvent.InputTuple,
      CC__Lottery_EnteredEvent.OutputTuple,
      CC__Lottery_EnteredEvent.OutputObject
    >;
    CC__Lottery_Entered: TypedContractEvent<
      CC__Lottery_EnteredEvent.InputTuple,
      CC__Lottery_EnteredEvent.OutputTuple,
      CC__Lottery_EnteredEvent.OutputObject
    >;

    "Calculated(uint256,string)": TypedContractEvent<
      CalculatedEvent.InputTuple,
      CalculatedEvent.OutputTuple,
      CalculatedEvent.OutputObject
    >;
    Calculated: TypedContractEvent<
      CalculatedEvent.InputTuple,
      CalculatedEvent.OutputTuple,
      CalculatedEvent.OutputObject
    >;

    "Claimed(uint256,uint256,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "CounterCalled(uint256,address,address)": TypedContractEvent<
      CounterCalledEvent.InputTuple,
      CounterCalledEvent.OutputTuple,
      CounterCalledEvent.OutputObject
    >;
    CounterCalled: TypedContractEvent<
      CounterCalledEvent.InputTuple,
      CounterCalledEvent.OutputTuple,
      CounterCalledEvent.OutputObject
    >;

    "DrawLottery(uint256,uint8[6])": TypedContractEvent<
      DrawLotteryEvent.InputTuple,
      DrawLotteryEvent.OutputTuple,
      DrawLotteryEvent.OutputObject
    >;
    DrawLottery: TypedContractEvent<
      DrawLotteryEvent.InputTuple,
      DrawLotteryEvent.OutputTuple,
      DrawLotteryEvent.OutputObject
    >;

    "PlatformAndLPShare(uint256,uint256,uint256)": TypedContractEvent<
      PlatformAndLPShareEvent.InputTuple,
      PlatformAndLPShareEvent.OutputTuple,
      PlatformAndLPShareEvent.OutputObject
    >;
    PlatformAndLPShare: TypedContractEvent<
      PlatformAndLPShareEvent.InputTuple,
      PlatformAndLPShareEvent.OutputTuple,
      PlatformAndLPShareEvent.OutputObject
    >;

    "PreviousRoundUnusedFundsCut(uint256,uint256,uint256)": TypedContractEvent<
      PreviousRoundUnusedFundsCutEvent.InputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputObject
    >;
    PreviousRoundUnusedFundsCut: TypedContractEvent<
      PreviousRoundUnusedFundsCutEvent.InputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputTuple,
      PreviousRoundUnusedFundsCutEvent.OutputObject
    >;

    "PriceWon(address,uint256,uint256,string)": TypedContractEvent<
      PriceWonEvent.InputTuple,
      PriceWonEvent.OutputTuple,
      PriceWonEvent.OutputObject
    >;
    PriceWon: TypedContractEvent<
      PriceWonEvent.InputTuple,
      PriceWonEvent.OutputTuple,
      PriceWonEvent.OutputObject
    >;

    "RewardClaimed(address,uint256,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "SetWinnerCount(uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SetWinnerCountEvent.InputTuple,
      SetWinnerCountEvent.OutputTuple,
      SetWinnerCountEvent.OutputObject
    >;
    SetWinnerCount: TypedContractEvent<
      SetWinnerCountEvent.InputTuple,
      SetWinnerCountEvent.OutputTuple,
      SetWinnerCountEvent.OutputObject
    >;

    "UserParticipated(address,uint256,uint256,uint8[6],uint256)": TypedContractEvent<
      UserParticipatedEvent.InputTuple,
      UserParticipatedEvent.OutputTuple,
      UserParticipatedEvent.OutputObject
    >;
    UserParticipated: TypedContractEvent<
      UserParticipatedEvent.InputTuple,
      UserParticipatedEvent.OutputTuple,
      UserParticipatedEvent.OutputObject
    >;

    "WinnersSetted(string)": TypedContractEvent<
      WinnersSettedEvent.InputTuple,
      WinnersSettedEvent.OutputTuple,
      WinnersSettedEvent.OutputObject
    >;
    WinnersSetted: TypedContractEvent<
      WinnersSettedEvent.InputTuple,
      WinnersSettedEvent.OutputTuple,
      WinnersSettedEvent.OutputObject
    >;
  };
}
