/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iCoinCaveLotterySol from "./ICoinCave_Lottery.sol";
export { ILink__factory } from "./ILink__factory";
