/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as usdtMockSol from "./USDT.mock.sol";
export type { usdtMockSol };
import type * as coSol from "./co.sol";
export type { coSol };
